### ISSUE TITLE
Malemute LS is broken

### ISSUE THREAD

**Issue by Esendis** [UmbraSpaceIndustries/Malemute#58]
Same as Karibou LS. (#1337)

**Comment by voicey99** [comment]
Malemute LS config isn't broken because it doesn't have an LS config. The only integration it has with USI-LS is with the recycler in the geology lab, which works perfectly.

**Comment by Esendis** [comment]
So it didn't have any LS to begin with? In that case,my bad.

**Comment by voicey99** [comment]
The Malemute is designed as a light runabout and exploration vehicle, for the heavier stuff with habitation parts you want the Karibou.
